version: "3.8"

services:
  app:
    image: registry.gitlab.com/tranvanchilong/async_web_gia:v0.2
    container_name: django_api_ecommerce
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "5007:8000"
    restart: always
    volumes:
      - ./app:/app